0/1 Knapsack

In [4]:
def knapsack(weight, value, W, n):
    if (W == 0) or (n == 0):
        return 0
    
    if (weight[n-1] <= W):
        return max(value[n-1] + knapsack(weight, value, W-weight[n-1], n-1), knapsack(weight, value, W, n-1))
    
    else:
        return knapsack(weight, value, W, n-1)

In [7]:
W = 6
profit = [1, 2, 3]
weight = [4, 5, 1]
print(knapsack(weight, profit, W, len(weight)))

5


Memorize

In [22]:
import numpy as np
arr = np.full((10,10), -1)
print(arr)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


In [26]:
def mem_knapsack(weight, value, W, n):
    if arr[n][W] != -1:
        return arr[n][W]
    
    if weight[n-1] <= W:
        arr[n][W] = max(value[n-1] + knapsack(weight, value, W-weight[n-1], n-1), 
                        knapsack(weight, value, W, n-1)) 
        return arr[n][W]
    else:
        arr[n][W] = knapsack(weight, value, W, n-1)
        return arr[n][W]

In [27]:
print(mem_knapsack(weight, profit, W, len(weight)))

5


In [28]:
print(arr)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  5 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
