0/1 Knapsack

In [1]:
def knapsack(weight, value, W, n):
    if (W == 0) or (n == 0):
        return 0
    
    if (weight[n-1] <= W):
        return max(value[n-1] + knapsack(weight, value, W-weight[n-1], n-1), knapsack(weight, value, W, n-1))
    
    else:
        return knapsack(weight, value, W, n-1)

In [2]:
W = 6
profit = [1, 2, 3]
weight = [4, 5, 1]
print(knapsack(weight, profit, W, len(weight)))

5


Memorize

In [3]:
import numpy as np
arr = np.full((10,10), -1)
print(arr)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


In [4]:
def mem_knapsack(weight, value, W, n):
    if arr[n][W] != -1:
        return arr[n][W]
    
    if weight[n-1] <= W:
        arr[n][W] = max(value[n-1] + knapsack(weight, value, W-weight[n-1], n-1), 
                        knapsack(weight, value, W, n-1)) 
        return arr[n][W]
    else:
        arr[n][W] = knapsack(weight, value, W, n-1)
        return arr[n][W]

In [5]:
print(mem_knapsack(weight, profit, W, len(weight)))

5


In [6]:
print(arr)

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1  5 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


numpy and row, col init

In [7]:
arr = np.zeros((3,4))

In [8]:
arr[0, :] = 1
arr[:, 0] = 1
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [16]:
W = 6
n = 2
memo = [[-1] * (W + 1) for _ in range(n + 1)]
memo

[[-1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1]]

top down dp

In [31]:
# W = 7
weight = [1,3,4,7,2,5]
values = [21,45,6,7,34,5]
n = len(weight)
dp = np.zeros((n+1,W+1))
dp

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [25]:
def dp_knapsack(weight, values, W, n):

    for i in range(n+1):
        for j in range(W+1):
            if (n == 0) or (W == 0):
                dp[i][j]

            pick = 0

            if weight[i-1] <= j:
                pick = values[i-1] + dp[i-1][j-weight[i-1]]

            not_pick = dp[i-1][j]

            dp[i][j] = max(pick, not_pick)
    return dp[n][W]


In [23]:
def generate(W):
    dp = dp_knapsack(weight, values, W, n)
    print(dp)

In [30]:
generate(W=6)

100.0


In [36]:
arr = np.empty((3,4))

In [37]:
arr

array([[21., 21., 21., 21.],
       [21., 21., 21., 21.],
       [21., 34., 21., 34.]])